# Generated by Django 5.0.6 on 2024-07-05 08:03

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reasons', tinymce.models.HTMLField()),
                ('leave_type', models.CharField(choices=[('sick', 'sick'), ('casual', 'casual'), ('emergency', 'emergency'), ('others', 'others')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'ppproved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
