# Generated by Django 5.0.3 on 2024-07-09 08:58

import trix.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reasons',
            field=trix.fields.TrixField(),
        ),
    ]
