# Generated by Django 5.0.3 on 2024-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reasons',
            field=models.TextField(),
        ),
    ]
