# Generated by Django 5.0.3 on 2024-07-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leave_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': [('can_view_all', 'Can View All Data'), ('can_view_own_department', 'Can View Own Department Data'), ('can_view_own_branch', 'Can View Own Branch Data'), ('can_view_own', 'Can View Own Data'), ('can_add_all', 'Can Add All Data'), ('can_add_own_department', 'Can Add Own Department Data'), ('can_add_own_branch', 'Can Add Own Branch Data'), ('can_add_own', 'Can Add Own Data'), ('can_change_all', 'Can Change All Data'), ('can_change_own_department', 'Can Change Own Department Data'), ('can_change_own_branch', 'Can Change Own Branch Data'), ('can_change_own', 'Can Change Own Data'), ('can_delete_all', 'Can Delete All Data'), ('can_delete_own_department', 'Can Delete Own Department Data'), ('can_delete_own_branch', 'Can Delete Own Branch Data'), ('can_delete_own', 'Can Delete Own Data')]},
        ),
    ]
