# Generated by Django 5.0.3 on 2024-07-19 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
